### ISSUE TITLE
When going from Lobby back to Main Menu, and then hosting again, two Avatars are spawned

### ISSUE THREAD

**Issue by jakobbbb** [GooseGirlGames/space-job#129]
[129.webm](https://user-images.githubusercontent.com/26824491/178137756-48c662c6-d8b5-4fc7-a1cc-4ad89b5a0f5d.webm)

**Comment by jreeee** [comment]
we also add a new network manager with every scene transition... 
I've tried to fix it for a while now but this so convoluted that i couldn't get anywhere
