### ISSUE TITLE
Unborking FBX Models:

### ISSUE THREAD

**Issue by Fionn-the-goose** [GooseGirlGames/space-job#40]
- [x] Breach B Gone
- [x] CoffeeStuff
- [x] DeskObjects (DinoTest permutation??) 🦆
- [x] Chair
- [x] Couch🦆
- [x] ~~Happy_Goose~~
- [x] HullBreach🦆
- [x] MetalPlate
- [x] Mothership🦆
- [x] navTerminal
- [x] Pipewrench🦆
- [x] Scope
- [x] simpleFlaschlight🦆
- [x] VendingMachine

**Comment by jakobbbb** [comment]
i'll do the ones with the ducks, if that's okay :3
